trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: PowerShellTasks
  steps:
  - checkout: none
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "HOOOOLA 1"