trigger: none
pr:
  branches:
    include:
      - main
      - release
      - dev
  paths:
    include:
    - 'Clean.Sdk.Domain/*'
    - 'Clean.Sdk.Domain.Test/*'

pool:
  name: self-hosted
variables:
  mainProject: 'Clean.Sdk.Domain/Clean.Sdk.Domain.csproj'
  testProject: 'Clean.Sdk.Domain.Test/Clean.Sdk.Domain.Test.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
stages:
- stage:
  displayName: Build and Test Projects
  jobs:
  - job:
    displayName: 'Build and Test Projects Job'
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Install the nugget tools'
    - task: NuGetCommand@2
      displayName: 'Reestore nuggets for main project'
      inputs:
        restoreSolution: '$(mainProject)'
    - task: NuGetCommand@2
      displayName: 'Reestore nuggets for test project'
      inputs:
        restoreSolution: '$(testProject)'
    - task: DotNetCoreCLI@2
      displayName: Build Project
      inputs:
        command: 'build'
        projects: $(mainProject)
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    - task: DotNetCoreCLI@2
      displayName: Build Test Project
      inputs:
        command: 'build'
        projects: $(testProject)
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/test'
    - task: DotNetCoreCLI@2
      displayName: Run Test Project
      inputs:
        projects: $(testProject)
        command: 'test'
        testRunTitle: 'Run test project'